[package]
name = "del_line"
version = "0.1.1"
edition = "2021"
description = "Small binary to delete the given lines from a file."
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
